version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery --app=server.celery:app worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - db

volumes:
  pg_data:
  redis_data:
