version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./.env.example:/app/.env
    depends_on:
      - redis
      - db

volumes:
  pg_data:
  redis_data:
