# Generated by Django 4.2.3 on 2023-07-22 21:22

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unreleased', 'Unreleased'), ('released', 'Released')], default='unreleased', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.project')),
            ],
            options={
                'verbose_name': 'release',
                'verbose_name_plural': 'releases',
                'db_table': 'releases',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=25, unique=True)),
                ('estimated_time', models.DurationField()),
                ('logged_time', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='my_issues', to='users.user')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reported_issues', to='users.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='issues.project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='issues.release')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comments',
            },
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='release_project_id_version_key'),
        ),
    ]
