# Generated by Django 4.2.3 on 2023-09-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin'),
        ('issues', '0002_alter_issue_assignee_alter_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.user'),
            preserve_default=False,
        ),
    ]
