name: Tests

on: [push]  # yamllint disable-line rule:truthy

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_tracker
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -q
          python -m pip install -r requirements.txt -r requirements.dev.txt -q
      - name: Tests and linters
        env:
          DATABASE_DSN: postgresql://postgres:postgres@localhost:5432/task_tracker
          CELERY_BROKER_URL: redis://localhost:6379/1
          CELERY_RESULT_BACKEND: redis://localhost:6379/2
          ALLOWED_HOSTS: '*'
          DJANGO_SECRET_KEY: example_secret_key
          AUTH_SECRET: secret_example
          JWT_TOKEN_SECRET: jwt_example_secret
          EMAIL_HOST: fake_host
          EMAIL_HOST_USER: fake_email
          EMAIL_HOST_PASSWORD: fake
          EMAIL_PORT: 587
          EMAIL_USE_TLS: true
        run: |
          isort server manage.py
          flake8 server manage.py
          mypy server manage.py
          pytest server --cov=./ --cov-report=xml
          python manage.py check --fail-level=WARNING
          yamllint --strict .
